In [1]:
import pandas as pd
import re

In [2]:
data = pd.read_csv ("Crawling data.csv")

In [3]:
df = data

In [4]:
df = df.drop('date', axis=1)

In [5]:
df.head(50)

,Unnamed: 0,id,text
0,0,di_dimu54412940,Calon Presiden Indonesia Ganjar Pranowo bersil...
1,1,Monkdz25,*KODE ALAM DAN TANDA ZAMAN SIAPA PRESIDEN RI K...
2,2,Presiden_Swasta,@ch_chotimah2 Dulu waktu AHY calon gubernur di...
3,3,di_dimu54412940,"Sang calon presiden Indonesia, Ganjar Pranowo ..."
4,4,okezonenews,Banyak tokoh yang digadang-gadang jadi calon w...
5,5,Elena08041804,Ganjar Pranowo mengajak partai politik penduku...
6,6,andystwn4,Bakal calon presiden (bacapres) dari Partai Ge...
7,7,moomigi,@yodisss Seneng bgt nih pasti masyarakat Lombo...
8,8,mercifulove,Bakal calon presiden yang juga Menteri Pertaha...
9,9,DkHurek,Mereka yg masih mempersoalkan seorang presiden...
10,10,catatanganjar,"""Kalau jadi pemimpin ya siap diinjak kepalanya..."
11,11,AdiJaya45860062,@Hasbil_Lbs pertemuan pak AHY dengan puan itu ...
12,12,Aryprasetyo85,@erickthohir Panen Elektabilitas \n\nSurvei te...
13,13,nusabalicom,Capres (Calon Presiden) dari PDI Perjuangan (P...
14,14,Reza90472792,Lah klu mereka kluar anies ga jadi calon presi...
15,15,redemptionPapua,TAIK saja\nSama CALON PRESIDEN Negri SULAP
16,16,inilahdotcom,Direktur Eksekutif Indonesia Political Review ...
17,17,LokoJoyo81,Nama Erick Thohir berada dalam posisi teratas ...
18,18,xylans,"Indonesia banget permisif begini. minta maaf, ..."
19,19,Bisniscom,Demokrat belum mengajukan apapun kepada PDIP k...
20,20,MasamuneMasamu2,"@inspiredrans Pantas seramai ini, yang disambu..."
21,21,Maad31,"@VIVAcoid Oke, fix\nIgnore calon presiden dari..."
22,22,okezonenews,"Selain bertemu dengan para pendukung, Bakal Ca..."
23,23,inilahdotcom,Bakal calon presiden usungan Partai Demokrasi ...
24,24,kumparan,Bakal calon presiden (bacapres) dari PDIP Ganj...
25,25,andystwn4,Kiai Asep menyebut di dalam kunjungan Menhan P...
26,26,Tejasukma71,@Munir_Timur @ganjarpranowo Kata Judika (juri ...
27,27,andystwn4,di dalam salah satu poin kerja sama calon pres...
28,28,itswincha,Nama @erickthohir berada dalam posisi teratas ...
29,29,andystwn4,kepada belasan ulama-kiai kondang asal Jatim t...
30,30,nfjmxpjjsgvrc,@yodisss memang beliau nih calon presiden yy b...
31,31,fachriman13,Calon Presiden PrabowoAja Subianto didoakan ol...
32,32,inilahdotcom,Direktur Eksekutif Indonesia Political Review ...
33,33,fachriman13,Dewan Syuro Majelis Rasulullah Habib Nabiel Al...
34,34,inspiredrans,PDIP dan PPP Nusa Tenggara Barat telah mempers...
35,35,Alkisah_Bapak,Bakal Calon Presiden (capres) PDI Perjuangan G...
36,36,opinimood,Keren nih moots PDIP dan PPP Nusa Tenggara Bar...
37,37,ginkonanba,Sangat meriah! Calon presiden dari partai PDIP...
38,38,Lia_Sandjaya,Bakal Calon Presiden (Bacapres) PDI Perjuangan...
39,39,kertaskataaa_,Para warga Lombok sangat berantusias sekali me...
40,40,sweetycookiepie,"Wah mantap nih Pak Ganjar lagi di Lombok, sema..."
41,41,humaini_hd,@Iam_Nobody_1145 @Siwahitam @Nast_1205 @ekowbo...
42,42,KakekHalal,Kunjungan Calon Presiden PDIP Ganjar Pranowo k...
43,43,SahabatTGB_ID,Momen menarik terpantau dalam lawatan bakal ca...
44,44,humaini_hd,@geloraco Jika ditanya 3 Sifat Calon Presiden ...
45,45,humaini_hd,@Taufiq_PD_DKI Jika ditanya 3 Sifat Calon Pres...
46,46,humaini_hd,@Gus_Raharjo Jika ditanya 3 Sifat Calon Presid...
47,47,humaini_hd,@bachrum_achmadi Jika ditanya 3 Sifat Calon Pr...
48,48,kangrust5,@ekokuntadhi1 Siapapun tidak mengatur APH…. Ma...
49,49,nxkedbibi,@blackgazed sebagai calon presiden rp saya har...

In [11]:
df.to_csv("data.csv", index =False)

In [12]:
data = pd.read_csv ("data.csv")

In [13]:
data.head()

,Unnamed: 0,id,text
0,0,di_dimu54412940,Calon Presiden Indonesia Ganjar Pranowo bersil...
1,1,Monkdz25,*KODE ALAM DAN TANDA ZAMAN SIAPA PRESIDEN RI K...
2,2,Presiden_Swasta,@ch_chotimah2 Dulu waktu AHY calon gubernur di...
3,3,di_dimu54412940,"Sang calon presiden Indonesia, Ganjar Pranowo ..."
4,4,okezonenews,Banyak tokoh yang digadang-gadang jadi calon w...

In [15]:
df.tail()

,Unnamed: 0,id,text
3137,3137,devan_r7,Ganjar Capres 2024 pilihan rakyat Indonesia\n#...
3138,3138,ShenoWirang,"Dua hal yang bisa menjegal si ""pembual"" Anies ..."
3139,3139,cnbcindonesia,Video: Naik Turun Elektabilitas Capres 2024 ht...
3140,3140,cerevisiatee,capres 2024 https://t.co/0uFSg1xtAQ
3141,3141,alessyeni_,@likechizu KIM NAMJOON CAPRES 2024!!!

In [17]:
combined_data = pd.concat([df.head(), df.tail()])

In [22]:
print(combined_data)

      Unnamed: 0               id  \
0              0  di_dimu54412940
1              1         Monkdz25
2              2  Presiden_Swasta
3              3  di_dimu54412940
4              4      okezonenews
3137        3137         devan_r7
3138        3138      ShenoWirang
3139        3139    cnbcindonesia
3140        3140     cerevisiatee
3141        3141       alessyeni_

                                                   text
0     Calon Presiden Indonesia Ganjar Pranowo bersil...
1     *KODE ALAM DAN TANDA ZAMAN SIAPA PRESIDEN RI K...
2     @ch_chotimah2 Dulu waktu AHY calon gubernur di...
3     Sang calon presiden Indonesia, Ganjar Pranowo ...
4     Banyak tokoh yang digadang-gadang jadi calon w...
3137  Ganjar Capres 2024 pilihan rakyat Indonesia\n#...
3138  Dua hal yang bisa menjegal si "pembual" Anies ...
3139  Video: Naik Turun Elektabilitas Capres 2024 ht...
3140                capres 2024 https://t.co/0uFSg1xtAQ
3141              @likechizu KIM NAMJOON CAPRES 2024!!!